name       : haskell-fingertree
version    : 0.1.4.2
release    : 3
source     :
    - https://hackage.haskell.org/package/fingertree-0.1.4.2/fingertree-0.1.4.2.tar.gz : 95a948341570bad5a9b2468c388c0eb2c20c57e10dd8fbfc994c7b8764b36a7f
license    : BSD-3-Clause
component  : programming.haskell
summary    : A general sequence representation with arbitrary annotations, for use as a base for implementations of various collection types
description: |
    A general sequence representation with arbitrary annotations, for use as a base for implementations of various collection types
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
