name       : haskell-fingertree
version    : 0.1.4.1
release    : 2
source     :
    - https://hackage.haskell.org/package/fingertree-0.1.4.1/fingertree-0.1.4.1.tar.gz : 9778dc162963c376f02239183e782673729d01a2e1e1dbf81924d80bf6f74ea4
license    : BSD-3-Clause
component  : programming.haskell
summary    : A general sequence representation with arbitrary annotations, for use as a base for implementations of various collection types
description: |
    A general sequence representation with arbitrary annotations, for use as a base for implementations of various collection types
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
